apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-configmap
  namespace: mon-namespace #permet d'utiliser un namespace précis, forcément à mettre dans le metadata
data:
  database_url: mongo-service.mon-namespace #en ajoutant ".mon-namespace" on utilise celui de ce namespace