from ./AgeEnfant        import Catégorie
from ./Bonjour          import Bonjour
from ./PaireImpaire     import PaireImpaire
from ./Premier          import Premier
from ./Puissance2       import Puissance
from ./Pyramide         import Pyramide
from ./Triangle2        import TriangleInversé
from ./TTC              import TTC
from ./TroisNoms        import Tri
from ./Conjecture       import Conjecture